//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAgencia.proxyTarifas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarifa", Namespace="http://schemas.datacontract.org/2004/07/SCTServiceWCF.Dominio")]
    [System.SerializableAttribute()]
    public partial class Tarifa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ERRORNUMEROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TARIFAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MENSAJEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MONEDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOM_TARIFAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PRECIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ERRORNUMERO {
            get {
                return this.ERRORNUMEROField;
            }
            set {
                if ((this.ERRORNUMEROField.Equals(value) != true)) {
                    this.ERRORNUMEROField = value;
                    this.RaisePropertyChanged("ERRORNUMERO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TARIFA {
            get {
                return this.ID_TARIFAField;
            }
            set {
                if ((this.ID_TARIFAField.Equals(value) != true)) {
                    this.ID_TARIFAField = value;
                    this.RaisePropertyChanged("ID_TARIFA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENSAJE {
            get {
                return this.MENSAJEField;
            }
            set {
                if ((object.ReferenceEquals(this.MENSAJEField, value) != true)) {
                    this.MENSAJEField = value;
                    this.RaisePropertyChanged("MENSAJE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MONEDA {
            get {
                return this.MONEDAField;
            }
            set {
                if ((object.ReferenceEquals(this.MONEDAField, value) != true)) {
                    this.MONEDAField = value;
                    this.RaisePropertyChanged("MONEDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_TARIFA {
            get {
                return this.NOM_TARIFAField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_TARIFAField, value) != true)) {
                    this.NOM_TARIFAField = value;
                    this.RaisePropertyChanged("NOM_TARIFA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PRECIO {
            get {
                return this.PRECIOField;
            }
            set {
                if ((this.PRECIOField.Equals(value) != true)) {
                    this.PRECIOField = value;
                    this.RaisePropertyChanged("PRECIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyTarifas.ITarifa")]
    public interface ITarifa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarifa/RegistrarTarifa", ReplyAction="http://tempuri.org/ITarifa/RegistrarTarifaResponse")]
        WebAgencia.proxyTarifas.Tarifa RegistrarTarifa(string NOM_TARIFA, decimal PRECIO, string MONEDA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarifa/ModificarTarifa", ReplyAction="http://tempuri.org/ITarifa/ModificarTarifaResponse")]
        WebAgencia.proxyTarifas.Tarifa ModificarTarifa(int ID_TARIFA, string NOM_TARIFA, decimal PRECIO, string MONEDA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarifa/EliminarTarifa", ReplyAction="http://tempuri.org/ITarifa/EliminarTarifaResponse")]
        void EliminarTarifa(int ID_TARIFA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarifa/ObtenerTarifa", ReplyAction="http://tempuri.org/ITarifa/ObtenerTarifaResponse")]
        WebAgencia.proxyTarifas.Tarifa ObtenerTarifa(int ID_TARIFA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarifa/ListarTarifa", ReplyAction="http://tempuri.org/ITarifa/ListarTarifaResponse")]
        WebAgencia.proxyTarifas.Tarifa[] ListarTarifa();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITarifaChannel : WebAgencia.proxyTarifas.ITarifa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TarifaClient : System.ServiceModel.ClientBase<WebAgencia.proxyTarifas.ITarifa>, WebAgencia.proxyTarifas.ITarifa {
        
        public TarifaClient() {
        }
        
        public TarifaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TarifaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TarifaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TarifaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAgencia.proxyTarifas.Tarifa RegistrarTarifa(string NOM_TARIFA, decimal PRECIO, string MONEDA) {
            return base.Channel.RegistrarTarifa(NOM_TARIFA, PRECIO, MONEDA);
        }
        
        public WebAgencia.proxyTarifas.Tarifa ModificarTarifa(int ID_TARIFA, string NOM_TARIFA, decimal PRECIO, string MONEDA) {
            return base.Channel.ModificarTarifa(ID_TARIFA, NOM_TARIFA, PRECIO, MONEDA);
        }
        
        public void EliminarTarifa(int ID_TARIFA) {
            base.Channel.EliminarTarifa(ID_TARIFA);
        }
        
        public WebAgencia.proxyTarifas.Tarifa ObtenerTarifa(int ID_TARIFA) {
            return base.Channel.ObtenerTarifa(ID_TARIFA);
        }
        
        public WebAgencia.proxyTarifas.Tarifa[] ListarTarifa() {
            return base.Channel.ListarTarifa();
        }
    }
}
