//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4963
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.CompactFramework.Design.Data generó automáticamente este código fuente, versión=2.0.50727.4963.
// 
namespace ConsetturMobile.wsConsettur {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsMobileSoap", Namespace="http://tempuri.org/")]
    public partial class WsMobile : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WsMobile() {
            this.Url = "http://172.16.12.6/WS_SCT/WsMobile.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario ValidaUsuario(string userName, string pwd) {
            object[] results = this.Invoke("ValidaUsuario", new object[] {
                        userName,
                        pwd});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidaUsuario(string userName, string pwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidaUsuario", new object[] {
                        userName,
                        pwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public Usuario EndValidaUsuario(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscar_tx_control_cabecera", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaccion buscar_tx_control_cabecera(string codigoBarras, string usuario) {
            object[] results = this.Invoke("buscar_tx_control_cabecera", new object[] {
                        codigoBarras,
                        usuario});
            return ((Transaccion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginbuscar_tx_control_cabecera(string codigoBarras, string usuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("buscar_tx_control_cabecera", new object[] {
                        codigoBarras,
                        usuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public Transaccion Endbuscar_tx_control_cabecera(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Transaccion)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscar_vehiculos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vehiculo buscar_vehiculos(string placa) {
            object[] results = this.Invoke("buscar_vehiculos", new object[] {
                        placa});
            return ((Vehiculo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginbuscar_vehiculos(string placa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("buscar_vehiculos", new object[] {
                        placa}, callback, asyncState);
        }
        
        /// <remarks/>
        public Vehiculo Endbuscar_vehiculos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Vehiculo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscar_conductor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Conductor buscar_conductor(string documento) {
            object[] results = this.Invoke("buscar_conductor", new object[] {
                        documento});
            return ((Conductor)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginbuscar_conductor(string documento, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("buscar_conductor", new object[] {
                        documento}, callback, asyncState);
        }
        
        /// <remarks/>
        public Conductor Endbuscar_conductor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Conductor)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verificar_conexion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verificar_conexion() {
            object[] results = this.Invoke("verificar_conexion", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginverificar_conexion(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("verificar_conexion", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endverificar_conexion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listar_otros_pasajeros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OtrosPasajeros[] listar_otros_pasajeros(string buscar) {
            object[] results = this.Invoke("listar_otros_pasajeros", new object[] {
                        buscar});
            return ((OtrosPasajeros[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlistar_otros_pasajeros(string buscar, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listar_otros_pasajeros", new object[] {
                        buscar}, callback, asyncState);
        }
        
        /// <remarks/>
        public OtrosPasajeros[] Endlistar_otros_pasajeros(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OtrosPasajeros[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscar_ticket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TicketDetalle buscar_ticket(TransaccionDetalle ticket) {
            object[] results = this.Invoke("buscar_ticket", new object[] {
                        ticket});
            return ((TicketDetalle)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginbuscar_ticket(TransaccionDetalle ticket, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("buscar_ticket", new object[] {
                        ticket}, callback, asyncState);
        }
        
        /// <remarks/>
        public TicketDetalle Endbuscar_ticket(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TicketDetalle)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cerrar_transaccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaccion cerrar_transaccion(Transaccion transaccion) {
            object[] results = this.Invoke("cerrar_transaccion", new object[] {
                        transaccion});
            return ((Transaccion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincerrar_transaccion(Transaccion transaccion, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cerrar_transaccion", new object[] {
                        transaccion}, callback, asyncState);
        }
        
        /// <remarks/>
        public Transaccion Endcerrar_transaccion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Transaccion)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrar_otros_pasajeros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransaccionDetalleVarios registrar_otros_pasajeros(TransaccionDetalleVarios otros) {
            object[] results = this.Invoke("registrar_otros_pasajeros", new object[] {
                        otros});
            return ((TransaccionDetalleVarios)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginregistrar_otros_pasajeros(TransaccionDetalleVarios otros, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("registrar_otros_pasajeros", new object[] {
                        otros}, callback, asyncState);
        }
        
        /// <remarks/>
        public TransaccionDetalleVarios Endregistrar_otros_pasajeros(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TransaccionDetalleVarios)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminar_Lectura_Ticket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Mensaje eliminar_Lectura_Ticket(string idTx, string codBarraTicket) {
            object[] results = this.Invoke("eliminar_Lectura_Ticket", new object[] {
                        idTx,
                        codBarraTicket});
            return ((Mensaje)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begineliminar_Lectura_Ticket(string idTx, string codBarraTicket, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("eliminar_Lectura_Ticket", new object[] {
                        idTx,
                        codBarraTicket}, callback, asyncState);
        }
        
        /// <remarks/>
        public Mensaje Endeliminar_Lectura_Ticket(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Mensaje)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cancelar_transaccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaccion cancelar_transaccion(Transaccion transaccion) {
            object[] results = this.Invoke("cancelar_transaccion", new object[] {
                        transaccion});
            return ((Transaccion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincancelar_transaccion(Transaccion transaccion, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelar_transaccion", new object[] {
                        transaccion}, callback, asyncState);
        }
        
        /// <remarks/>
        public Transaccion Endcancelar_transaccion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Transaccion)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consulta_embarques", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResumenLectura[] consulta_embarques(short id_centro, string fecha) {
            object[] results = this.Invoke("consulta_embarques", new object[] {
                        id_centro,
                        fecha});
            return ((ResumenLectura[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginconsulta_embarques(short id_centro, string fecha, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consulta_embarques", new object[] {
                        id_centro,
                        fecha}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResumenLectura[] Endconsulta_embarques(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResumenLectura[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sincronizacion_offline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaccion sincronizacion_offline(Transaccion transOfflne) {
            object[] results = this.Invoke("sincronizacion_offline", new object[] {
                        transOfflne});
            return ((Transaccion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsincronizacion_offline(Transaccion transOfflne, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sincronizacion_offline", new object[] {
                        transOfflne}, callback, asyncState);
        }
        
        /// <remarks/>
        public Transaccion Endsincronizacion_offline(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Transaccion)(results[0]));
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private string loginUserField;
        
        private string passwordField;
        
        private string usuarioField;
        
        private bool mobileField;
        
        private bool activoField;
        
        private string mensajeField;
        
        private short errNumberField;
        
        private Centros[] centrosField;
        
        /// <comentarios/>
        public string loginUser {
            get {
                return this.loginUserField;
            }
            set {
                this.loginUserField = value;
            }
        }
        
        /// <comentarios/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public bool mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <comentarios/>
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public short errNumber {
            get {
                return this.errNumberField;
            }
            set {
                this.errNumberField = value;
            }
        }
        
        /// <comentarios/>
        public Centros[] centros {
            get {
                return this.centrosField;
            }
            set {
                this.centrosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Centros {
        
        private int idcentroField;
        
        private string centroField;
        
        /// <comentarios/>
        public int idcentro {
            get {
                return this.idcentroField;
            }
            set {
                this.idcentroField = value;
            }
        }
        
        /// <comentarios/>
        public string centro {
            get {
                return this.centroField;
            }
            set {
                this.centroField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResumenLectura {
        
        private short contadorField;
        
        private string fechaField;
        
        private string idTxField;
        
        private string nroUnidadField;
        
        private string placaField;
        
        private string horaInicioField;
        
        private string horaFinField;
        
        private string conductorField;
        
        private short cantidadField;
        
        private short paxField;
        
        private string usuarioField;
        
        private string centroField;
        
        private string tiempoField;
        
        private string estadoField;
        
        /// <comentarios/>
        public short contador {
            get {
                return this.contadorField;
            }
            set {
                this.contadorField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public string idTx {
            get {
                return this.idTxField;
            }
            set {
                this.idTxField = value;
            }
        }
        
        /// <comentarios/>
        public string nroUnidad {
            get {
                return this.nroUnidadField;
            }
            set {
                this.nroUnidadField = value;
            }
        }
        
        /// <comentarios/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <comentarios/>
        public string horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
            }
        }
        
        /// <comentarios/>
        public string horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
            }
        }
        
        /// <comentarios/>
        public string conductor {
            get {
                return this.conductorField;
            }
            set {
                this.conductorField = value;
            }
        }
        
        /// <comentarios/>
        public short cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <comentarios/>
        public short pax {
            get {
                return this.paxField;
            }
            set {
                this.paxField = value;
            }
        }
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string centro {
            get {
                return this.centroField;
            }
            set {
                this.centroField = value;
            }
        }
        
        /// <comentarios/>
        public string tiempo {
            get {
                return this.tiempoField;
            }
            set {
                this.tiempoField = value;
            }
        }
        
        /// <comentarios/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Mensaje {
        
        private short errNumberField;
        
        private string mensajeField;
        
        /// <comentarios/>
        public short errNumber {
            get {
                return this.errNumberField;
            }
            set {
                this.errNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TicketDetalle {
        
        private string codigoBarrasField;
        
        private string tipoTarifaField;
        
        private string tarifaField;
        
        private string fechaVentaField;
        
        private string fechaExpiracionField;
        
        private string puntoVentaField;
        
        private short flagEstadoField;
        
        private string colorField;
        
        private short errNumberField;
        
        private string mensajeField;
        
        /// <comentarios/>
        public string codigoBarras {
            get {
                return this.codigoBarrasField;
            }
            set {
                this.codigoBarrasField = value;
            }
        }
        
        /// <comentarios/>
        public string tipoTarifa {
            get {
                return this.tipoTarifaField;
            }
            set {
                this.tipoTarifaField = value;
            }
        }
        
        /// <comentarios/>
        public string tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
            }
        }
        
        /// <comentarios/>
        public string fechaVenta {
            get {
                return this.fechaVentaField;
            }
            set {
                this.fechaVentaField = value;
            }
        }
        
        /// <comentarios/>
        public string fechaExpiracion {
            get {
                return this.fechaExpiracionField;
            }
            set {
                this.fechaExpiracionField = value;
            }
        }
        
        /// <comentarios/>
        public string puntoVenta {
            get {
                return this.puntoVentaField;
            }
            set {
                this.puntoVentaField = value;
            }
        }
        
        /// <comentarios/>
        public short flagEstado {
            get {
                return this.flagEstadoField;
            }
            set {
                this.flagEstadoField = value;
            }
        }
        
        /// <comentarios/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <comentarios/>
        public short errNumber {
            get {
                return this.errNumberField;
            }
            set {
                this.errNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OtrosPasajeros {
        
        private short idVariosField;
        
        private string descripcionField;
        
        private short errNumberField;
        
        private string mensajeField;
        
        /// <comentarios/>
        public short idVarios {
            get {
                return this.idVariosField;
            }
            set {
                this.idVariosField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public short errNumber {
            get {
                return this.errNumberField;
            }
            set {
                this.errNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Conductor {
        
        private short idChoferField;
        
        private string nombresField;
        
        private string dniField;
        
        private string cargoField;
        
        private string empresaField;
        
        private string licenciaField;
        
        private short errNumberField;
        
        private string mensajeField;
        
        /// <comentarios/>
        public short idChofer {
            get {
                return this.idChoferField;
            }
            set {
                this.idChoferField = value;
            }
        }
        
        /// <comentarios/>
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <comentarios/>
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
            }
        }
        
        /// <comentarios/>
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
            }
        }
        
        /// <comentarios/>
        public string empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
        
        /// <comentarios/>
        public string licencia {
            get {
                return this.licenciaField;
            }
            set {
                this.licenciaField = value;
            }
        }
        
        /// <comentarios/>
        public short errNumber {
            get {
                return this.errNumberField;
            }
            set {
                this.errNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Vehiculo {
        
        private short idVehiculoField;
        
        private string placaField;
        
        private string modeloField;
        
        private string marcaField;
        
        private string annioFabricacionField;
        
        private string nroUnidadField;
        
        private string empresaField;
        
        private short errNumberField;
        
        private string mensajeField;
        
        /// <comentarios/>
        public short idVehiculo {
            get {
                return this.idVehiculoField;
            }
            set {
                this.idVehiculoField = value;
            }
        }
        
        /// <comentarios/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <comentarios/>
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <comentarios/>
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <comentarios/>
        public string annioFabricacion {
            get {
                return this.annioFabricacionField;
            }
            set {
                this.annioFabricacionField = value;
            }
        }
        
        /// <comentarios/>
        public string nroUnidad {
            get {
                return this.nroUnidadField;
            }
            set {
                this.nroUnidadField = value;
            }
        }
        
        /// <comentarios/>
        public string empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
        
        /// <comentarios/>
        public short errNumber {
            get {
                return this.errNumberField;
            }
            set {
                this.errNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransaccionDetalleVarios {
        
        private string idTXField;
        
        private short idVariosField;
        
        private string descripcionField;
        
        private short cantidadField;
        
        private string observacionesField;
        
        private string usuarioField;
        
        private short idVehiculoField;
        
        private short idChoferField;
        
        private short idCentroField;
        
        private short errNumberField;
        
        private string mensajeField;
        
        /// <comentarios/>
        public string idTX {
            get {
                return this.idTXField;
            }
            set {
                this.idTXField = value;
            }
        }
        
        /// <comentarios/>
        public short idVarios {
            get {
                return this.idVariosField;
            }
            set {
                this.idVariosField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public short cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <comentarios/>
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public short idVehiculo {
            get {
                return this.idVehiculoField;
            }
            set {
                this.idVehiculoField = value;
            }
        }
        
        /// <comentarios/>
        public short idChofer {
            get {
                return this.idChoferField;
            }
            set {
                this.idChoferField = value;
            }
        }
        
        /// <comentarios/>
        public short idCentro {
            get {
                return this.idCentroField;
            }
            set {
                this.idCentroField = value;
            }
        }
        
        /// <comentarios/>
        public short errNumber {
            get {
                return this.errNumberField;
            }
            set {
                this.errNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransaccionDetalle {
        
        private string idTXField;
        
        private string codigoBarrasTicketField;
        
        private short nroLecturaField;
        
        private string observacionesField;
        
        private string tarifaField;
        
        private string usuarioField;
        
        private short idVehiculoField;
        
        private short idChoferField;
        
        private short idCentroField;
        
        private short errNumberField;
        
        private string mensajeField;
        
        /// <comentarios/>
        public string idTX {
            get {
                return this.idTXField;
            }
            set {
                this.idTXField = value;
            }
        }
        
        /// <comentarios/>
        public string codigoBarrasTicket {
            get {
                return this.codigoBarrasTicketField;
            }
            set {
                this.codigoBarrasTicketField = value;
            }
        }
        
        /// <comentarios/>
        public short nroLectura {
            get {
                return this.nroLecturaField;
            }
            set {
                this.nroLecturaField = value;
            }
        }
        
        /// <comentarios/>
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <comentarios/>
        public string tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
            }
        }
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public short idVehiculo {
            get {
                return this.idVehiculoField;
            }
            set {
                this.idVehiculoField = value;
            }
        }
        
        /// <comentarios/>
        public short idChofer {
            get {
                return this.idChoferField;
            }
            set {
                this.idChoferField = value;
            }
        }
        
        /// <comentarios/>
        public short idCentro {
            get {
                return this.idCentroField;
            }
            set {
                this.idCentroField = value;
            }
        }
        
        /// <comentarios/>
        public short errNumber {
            get {
                return this.errNumberField;
            }
            set {
                this.errNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Transaccion {
        
        private string choferField;
        
        private string docChoferField;
        
        private string placaVehiculoField;
        
        private TransaccionDetalle[] transaccionDetalleField;
        
        private TransaccionDetalleVarios[] transaccionDetalleVariosField;
        
        private short errNumberField;
        
        private string mensajeField;
        
        private string idTxField;
        
        private System.DateTime fechaRegistroField;
        
        private short idVehiculoField;
        
        private short idChoferField;
        
        private string loginUserField;
        
        private short idCentroField;
        
        private System.DateTime horaInicioField;
        
        private System.DateTime horaFinField;
        
        private bool flagSubidaField;
        
        private short flagEstadoField;
        
        /// <comentarios/>
        public string chofer {
            get {
                return this.choferField;
            }
            set {
                this.choferField = value;
            }
        }
        
        /// <comentarios/>
        public string docChofer {
            get {
                return this.docChoferField;
            }
            set {
                this.docChoferField = value;
            }
        }
        
        /// <comentarios/>
        public string placaVehiculo {
            get {
                return this.placaVehiculoField;
            }
            set {
                this.placaVehiculoField = value;
            }
        }
        
        /// <comentarios/>
        public TransaccionDetalle[] transaccionDetalle {
            get {
                return this.transaccionDetalleField;
            }
            set {
                this.transaccionDetalleField = value;
            }
        }
        
        /// <comentarios/>
        public TransaccionDetalleVarios[] transaccionDetalleVarios {
            get {
                return this.transaccionDetalleVariosField;
            }
            set {
                this.transaccionDetalleVariosField = value;
            }
        }
        
        /// <comentarios/>
        public short errNumber {
            get {
                return this.errNumberField;
            }
            set {
                this.errNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public string idTx {
            get {
                return this.idTxField;
            }
            set {
                this.idTxField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <comentarios/>
        public short idVehiculo {
            get {
                return this.idVehiculoField;
            }
            set {
                this.idVehiculoField = value;
            }
        }
        
        /// <comentarios/>
        public short idChofer {
            get {
                return this.idChoferField;
            }
            set {
                this.idChoferField = value;
            }
        }
        
        /// <comentarios/>
        public string loginUser {
            get {
                return this.loginUserField;
            }
            set {
                this.loginUserField = value;
            }
        }
        
        /// <comentarios/>
        public short idCentro {
            get {
                return this.idCentroField;
            }
            set {
                this.idCentroField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
            }
        }
        
        /// <comentarios/>
        public bool flagSubida {
            get {
                return this.flagSubidaField;
            }
            set {
                this.flagSubidaField = value;
            }
        }
        
        /// <comentarios/>
        public short flagEstado {
            get {
                return this.flagEstadoField;
            }
            set {
                this.flagEstadoField = value;
            }
        }
    }
}
