//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEmpresaService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/SCTServiceWCF.Dominio")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIRECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMPRESAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_EMPRESAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestEmpresaService.ServiceReference1.Empresa LISTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCION {
            get {
                return this.DIRECCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DIRECCIONField, value) != true)) {
                    this.DIRECCIONField = value;
                    this.RaisePropertyChanged("DIRECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESAField, value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_EMPRESA {
            get {
                return this.ID_EMPRESAField;
            }
            set {
                if ((this.ID_EMPRESAField.Equals(value) != true)) {
                    this.ID_EMPRESAField = value;
                    this.RaisePropertyChanged("ID_EMPRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestEmpresaService.ServiceReference1.Empresa LISTA {
            get {
                return this.LISTAField;
            }
            set {
                if ((object.ReferenceEquals(this.LISTAField, value) != true)) {
                    this.LISTAField = value;
                    this.RaisePropertyChanged("LISTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO {
            get {
                return this.TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONOField, value) != true)) {
                    this.TELEFONOField = value;
                    this.RaisePropertyChanged("TELEFONO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEmpresas")]
    public interface IEmpresas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresas/CrearEmpresa", ReplyAction="http://tempuri.org/IEmpresas/CrearEmpresaResponse")]
        TestEmpresaService.ServiceReference1.Empresa CrearEmpresa(string empresa, string ruc, string telefono, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresas/ObtenerEmpresa", ReplyAction="http://tempuri.org/IEmpresas/ObtenerEmpresaResponse")]
        TestEmpresaService.ServiceReference1.Empresa ObtenerEmpresa(int codigo, string empresa, string ruc, string telefono, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresas/ModificarEmpresa", ReplyAction="http://tempuri.org/IEmpresas/ModificarEmpresaResponse")]
        TestEmpresaService.ServiceReference1.Empresa ModificarEmpresa(int codigo, string empresa, string ruc, string telefono, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresas/EliminarEmpresa", ReplyAction="http://tempuri.org/IEmpresas/EliminarEmpresaResponse")]
        void EliminarEmpresa(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresas/ListarEmpresa", ReplyAction="http://tempuri.org/IEmpresas/ListarEmpresaResponse")]
        TestEmpresaService.ServiceReference1.Empresa[] ListarEmpresa();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpresasChannel : TestEmpresaService.ServiceReference1.IEmpresas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresasClient : System.ServiceModel.ClientBase<TestEmpresaService.ServiceReference1.IEmpresas>, TestEmpresaService.ServiceReference1.IEmpresas {
        
        public EmpresasClient() {
        }
        
        public EmpresasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestEmpresaService.ServiceReference1.Empresa CrearEmpresa(string empresa, string ruc, string telefono, string direccion) {
            return base.Channel.CrearEmpresa(empresa, ruc, telefono, direccion);
        }
        
        public TestEmpresaService.ServiceReference1.Empresa ObtenerEmpresa(int codigo, string empresa, string ruc, string telefono, string direccion) {
            return base.Channel.ObtenerEmpresa(codigo, empresa, ruc, telefono, direccion);
        }
        
        public TestEmpresaService.ServiceReference1.Empresa ModificarEmpresa(int codigo, string empresa, string ruc, string telefono, string direccion) {
            return base.Channel.ModificarEmpresa(codigo, empresa, ruc, telefono, direccion);
        }
        
        public void EliminarEmpresa(int codigo) {
            base.Channel.EliminarEmpresa(codigo);
        }
        
        public TestEmpresaService.ServiceReference1.Empresa[] ListarEmpresa() {
            return base.Channel.ListarEmpresa();
        }
    }
}
